POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"name": "Alf Fonti",
	"number": "033-1234567"
}

###

POST https://fullstackopen-phonebook.cyclic.app/api/persons
Content-Type: application/json

{
	"name": "Alf Fonti",
	"number": "123"
}
